In [1]:
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
PROCESSED_DATA = Path("../data/processed/")
FIGURES_PATH = Path("../reports/figures/")
INTERIM_DATA = Path("../data/interim/")

In [10]:
df = pd.read_parquet(INTERIM_DATA/ "merge_data.parquet")

In [11]:
df.columns

Index(['transaction_id', 'timestamp', 'user_id', 'merchant_id', 'amount',
       'channel', 'currency', 'device', 'location', 'payment_method',
       'is_international', 'session_length_seconds', 'is_first_time_merchant',
       'is_fraud', 'age', 'sex', 'education', 'primary_source_of_income',
       'sum_of_monthly_installments', 'sum_of_monthly_expenses',
       'country_user', 'signup_date', 'risk_score', 'category',
       'country_merchant', 'trust_score', 'number_of_alerts_last_6_months',
       'avg_transaction_amount', 'account_age_months', 'has_fraud_history'],
      dtype='object')

In [12]:
df.drop(columns=['currency','user_id',	'merchant_id','location'], inplace=True)

In [13]:
df['education'] = df['education'].fillna('Missing')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   transaction_id                  500000 non-null  object
 1   timestamp                       500000 non-null  datetime64[ns]
 2   amount                          500000 non-null  float64
 3   channel                         500000 non-null  object
 4   device                          500000 non-null  object
 5   payment_method                  500000 non-null  object
 6   is_international                500000 non-null  int64
 7   session_length_seconds          500000 non-null  int64
 8   is_first_time_merchant          500000 non-null  int64
 9   is_fraud                        500000 non-null  int64
 10  age                             500000 non-null  int64
 11  sex                             500000 non-null  object
 12  education                       500000 non-null  object
 13  primary_source_of_income        500000 non-null  object
 14  sum_of_monthly_installments     500000 non-null  float64
 15  sum_of_monthly_expenses         500000 non-null  float64
 16  country_user                    500000 non-null  object
 17  signup_date                     500000 non-null  object
 18  risk_score                      500000 non-null  float64
 19  category                        500000 non-null  object
 20  country_merchant                500000 non-null  object
 21  trust_score                     500000 non-null  float64
 22  number_of_alerts_last_6_months  500000 non-null  int64
 23  avg_transaction_amount          500000 non-null  float64
 24  account_age_months              500000 non-null  int64
 25  has_fraud_history               500000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(8), object(11)
memory usage: 99.2+ MB

In [15]:
df.drop(columns=["transaction_id"] , inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   timestamp                       500000 non-null  datetime64[ns]
 1   amount                          500000 non-null  float64
 2   channel                         500000 non-null  object
 3   device                          500000 non-null  object
 4   payment_method                  500000 non-null  object
 5   is_international                500000 non-null  int64
 6   session_length_seconds          500000 non-null  int64
 7   is_first_time_merchant          500000 non-null  int64
 8   is_fraud                        500000 non-null  int64
 9   age                             500000 non-null  int64
 10  sex                             500000 non-null  object
 11  education                       500000 non-null  object
 12  primary_source_of_income        500000 non-null  object
 13  sum_of_monthly_installments     500000 non-null  float64
 14  sum_of_monthly_expenses         500000 non-null  float64
 15  country_user                    500000 non-null  object
 16  signup_date                     500000 non-null  object
 17  risk_score                      500000 non-null  float64
 18  category                        500000 non-null  object
 19  country_merchant                500000 non-null  object
 20  trust_score                     500000 non-null  float64
 21  number_of_alerts_last_6_months  500000 non-null  int64
 22  avg_transaction_amount          500000 non-null  float64
 23  account_age_months              500000 non-null  int64
 24  has_fraud_history               500000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(8), object(10)
memory usage: 95.4+ MB

In [17]:
df["signup_date"] = pd.to_datetime(df["signup_date"])

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   timestamp                       500000 non-null  datetime64[ns]
 1   amount                          500000 non-null  float64
 2   channel                         500000 non-null  object
 3   device                          500000 non-null  object
 4   payment_method                  500000 non-null  object
 5   is_international                500000 non-null  int64
 6   session_length_seconds          500000 non-null  int64
 7   is_first_time_merchant          500000 non-null  int64
 8   is_fraud                        500000 non-null  int64
 9   age                             500000 non-null  int64
 10  sex                             500000 non-null  object
 11  education                       500000 non-null  object
 12  primary_source_of_income        500000 non-null  object
 13  sum_of_monthly_installments     500000 non-null  float64
 14  sum_of_monthly_expenses         500000 non-null  float64
 15  country_user                    500000 non-null  object
 16  signup_date                     500000 non-null  datetime64[ns]
 17  risk_score                      500000 non-null  float64
 18  category                        500000 non-null  object
 19  country_merchant                500000 non-null  object
 20  trust_score                     500000 non-null  float64
 21  number_of_alerts_last_6_months  500000 non-null  int64
 22  avg_transaction_amount          500000 non-null  float64
 23  account_age_months              500000 non-null  int64
 24  has_fraud_history               500000 non-null  int64
dtypes: datetime64[ns](2), float64(6), int64(8), object(9)
memory usage: 95.4+ MB

In [19]:
pd.get_dummies(df,columns=['education'], dtype=int)

,timestamp,amount,channel,device,payment_method,is_international,session_length_seconds,is_first_time_merchant,is_fraud,age,...,trust_score,number_of_alerts_last_6_months,avg_transaction_amount,account_age_months,has_fraud_history,education_Bachelor,education_High School,education_Master,education_Missing,education_PhD
0,2022-06-17 23:28:00,130.03,in-store,Android,debit_card,1,145,0,0,23,...,0.581711,3,74.97,23,1,1,0,0,0,0
1,2022-01-04 15:39:00,132.00,online,Android,debit_card,1,32,1,0,53,...,0.568933,2,56.92,23,0,0,0,0,0,1
2,2022-09-09 21:58:00,8.65,online,Android,credit_card,1,604,1,0,58,...,0.608070,5,98.93,75,0,1,0,0,0,0
3,2023-11-20 06:40:00,19.82,mobile,iOS,credit_card,0,1031,1,0,59,...,0.592656,4,21.60,82,0,0,0,1,0,0
4,2022-04-28 08:08:00,101.92,in-store,Android,credit_card,1,330,0,0,28,...,0.450223,4,60.61,82,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,2022-04-19 18:12:00,11.53,in-store,iOS,bank_transfer,1,916,1,0,50,...,0.295231,0,1.26,12,1,1,0,0,0,0
499996,2023-06-02 06:59:00,78.01,mobile,iOS,bank_transfer,1,527,0,0,35,...,0.700921,1,40.48,33,0,0,1,0,0,0
499997,2022-08-06 13:14:00,77.65,in-store,iOS,bank_transfer,1,351,0,0,37,...,0.797026,4,15.81,111,1,1,0,0,0,0
499998,2023-03-20 22:00:00,221.38,online,iOS,mobile_payment,1,887,0,0,22,...,1.000000,7,38.62,7,1,0,1,0,0,0
499999,2023-01-29 14:46:00,103.17,in-store,iOS,bank_transfer,1,1082,0,0,36,...,1.000000,3,41.86,65,0,0,0,0,1,0

In [22]:
categorical_cols = ["channel", "device", "payment_method" , "sex", "education", "primary_source_of_income","category"]

In [23]:
df_encoded = pd.get_dummies(df,columns=categorical_cols, dtype=int, drop_first=True)

In [24]:
df_encoded.shape

(500000, 42)

In [26]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 42 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   timestamp                              500000 non-null  datetime64[ns]
 1   amount                                 500000 non-null  float64
 2   is_international                       500000 non-null  int64
 3   session_length_seconds                 500000 non-null  int64
 4   is_first_time_merchant                 500000 non-null  int64
 5   is_fraud                               500000 non-null  int64
 6   age                                    500000 non-null  int64
 7   sum_of_monthly_installments            500000 non-null  float64
 8   sum_of_monthly_expenses                500000 non-null  float64
 9   country_user                           500000 non-null  object
 10  signup_date                            500000 non-null  datetime64[ns]
 11  risk_score                             500000 non-null  float64
 12  country_merchant                       500000 non-null  object
 13  trust_score                            500000 non-null  float64
 14  number_of_alerts_last_6_months         500000 non-null  int64
 15  avg_transaction_amount                 500000 non-null  float64
 16  account_age_months                     500000 non-null  int64
 17  has_fraud_history                      500000 non-null  int64
 18  channel_mobile                         500000 non-null  int64
 19  channel_online                         500000 non-null  int64
 20  device_Web                             500000 non-null  int64
 21  device_iOS                             500000 non-null  int64
 22  payment_method_credit_card             500000 non-null  int64
 23  payment_method_debit_card              500000 non-null  int64
 24  payment_method_mobile_payment          500000 non-null  int64
 25  sex_Male                               500000 non-null  int64
 26  sex_Other                              500000 non-null  int64
 27  education_High School                  500000 non-null  int64
 28  education_Master                       500000 non-null  int64
 29  education_Missing                      500000 non-null  int64
 30  education_PhD                          500000 non-null  int64
 31  primary_source_of_income_Employment    500000 non-null  int64
 32  primary_source_of_income_Retirement    500000 non-null  int64
 33  primary_source_of_income_Savings       500000 non-null  int64
 34  primary_source_of_income_Student Aid   500000 non-null  int64
 35  primary_source_of_income_Unemployment  500000 non-null  int64
 36  category_education                     500000 non-null  int64
 37  category_electronics                   500000 non-null  int64
 38  category_gaming                        500000 non-null  int64
 39  category_grocery                       500000 non-null  int64
 40  category_restaurants                   500000 non-null  int64
 41  category_travel                        500000 non-null  int64
dtypes: datetime64[ns](2), float64(6), int64(32), object(2)
memory usage: 160.2+ MB

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
df.columns

Index(['timestamp', 'amount', 'channel', 'device', 'payment_method',
       'is_international', 'session_length_seconds', 'is_first_time_merchant',
       'is_fraud', 'age', 'sex', 'education', 'primary_source_of_income',
       'sum_of_monthly_installments', 'sum_of_monthly_expenses',
       'country_user', 'signup_date', 'risk_score', 'category',
       'country_merchant', 'trust_score', 'number_of_alerts_last_6_months',
       'avg_transaction_amount', 'account_age_months', 'has_fraud_history'],
      dtype='object')

In [31]:
numerical_cols = ['amount','session_length_seconds','age', 'sum_of_monthly_installments', 'sum_of_monthly_expenses','risk_score','trust_score', 'number_of_alerts_last_6_months','avg_transaction_amount', 'account_age_months']

In [32]:
scaler=StandardScaler()

In [33]:
scaler.fit(df_encoded[numerical_cols])

StandardScaler()

In [34]:
df_encoded[numerical_cols] = scaler.transform(df_encoded[numerical_cols])

In [40]:
df_encoded[numerical_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
amount,500000.0,8.754597e-17,1.000001,-0.998501,-0.711047,-0.307171,0.385209,13.301386
session_length_seconds,500000.0,1.131397e-16,1.000001,-1.730265,-0.863634,-0.002920,0.863710,1.730340
age,500000.0,-1.078746e-16,1.000001,-1.691432,-0.844251,0.002931,0.850112,1.697293
sum_of_monthly_installments,500000.0,-3.996092e-17,1.000001,-0.992851,-0.704826,-0.309788,0.384313,9.437243
sum_of_monthly_expenses,500000.0,2.015224e-16,1.000001,-1.011412,-0.708905,-0.305532,0.400433,8.393723
risk_score,500000.0,6.262084e-16,1.000001,-3.345797,-0.685923,-0.007315,0.680532,3.324556
trust_score,500000.0,8.799859e-16,1.000001,-3.512875,-0.703903,0.076210,0.740188,1.630844
number_of_alerts_last_6_months,500000.0,2.137490e-17,1.000001,-1.775146,-0.613726,-0.033016,0.547694,3.451245
avg_transaction_amount,500000.0,-3.187992e-16,1.000001,-1.032761,-0.721915,-0.297725,0.446535,7.925149
account_age_months,500000.0,-2.053469e-17,1.000001,-1.661703,-0.883904,-0.016358,0.911018,1.718733

In [41]:
df_encoded.to_parquet(INTERIM_DATA/"df_encoded.parquet")

In [42]:
df_encoded.shape

(500000, 42)